--- 
- hosts: MySqlNodes
  tasks:
    - name: Remove the folder incase if any
      command: rm -rf /var/lib/mysql
      sudo: yes

    - name: install the latest version of Mysql-Server
      yum: name=mysql-server state=latest
      sudo: yes

    - name: install the latest version of Mysql-Python
      yum: name=MySQL-python state=latest
      sudo: yes

    
    - name: create a Mysql config file
      action: template src=/root/python/installations/mysql.cnf.j2 dest=/etc/my.cnf
      sudo: yes

    - name: change the file permissions
      command: chmod 0644 /etc/my.cnf
      sudo: yes


    - name: Make sure that the mysqllog directory exsists
      action: file path=/var/log/mysql state=directory
      sudo: yes

    - name: change the file permissions
      command: chown -R mysql:mysql /var/log/mysql
      sudo: yes

    - name: Start the mysql server
      action: service name=mysqld state=restarted enabled=yes
      sudo: yes
    - name: Find out the master log file name and position
      command: >
        /usr/bin/mysql -uroot
        -e "SHOW DATABASES;"
      register: databases
    - debug: var=databases.stdout_lines
    - mysql_user: user=replicator  password=password priv=*.*:'REPLICATION SLAVE' state=present
# Stop mysql slave thread
    - mysql_replication: mode=stopslave

       # Get master binlog file name and binlog position
    - mysql_replication: mode=getmaster

       # Change master to master server 192.168.1.1 and use binary log 'mysql-bin.000009' with position 4578
    - mysql_replication: mode=changemaster master_host=54.88.47.45  master_user=replicator master_password=password master_log_file=mysql-bin.000009 master_log_pos=4578
    - mysql_replication: mode=startslave
    - mysql_replication: mode=stopslave

       # Get master binlog file name and binlog position
    - mysql_replication: mode=getmaster

       # Change master to master server 192.168.1.1 and use binary log 'mysql-bin.000009' with position 4578
    - mysql_replication: mode=changemaster master_host=54.86.145.214  master_user=replicator master_password=password master_log_file=mysql-bin.000009 master_log_pos=4578
    - mysql_replication: mode=startslave
    - name: Start the mysql server
      action: service name=mysqld state=restarted enabled=yes
      sudo: yes

